server:
  port: 8082
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: ratingservice
  application:
    name: rating-service
  config:
    import: optional:configserver:http://localhost:8084

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

okta:
  oauth2:
    issuer: https://dev-38884440.okta.com/oauth2/default
    audience: api://default